title: The Republic of Agora
description: EMPOWER THE PUBLIC ♢ VOL.4 © MMXXI
baseurl: "/pen0" # the subpath of your site, e.g. /blog
url: "https://agorahub.github.io" # the base hostname & protocol for your site, e.g. http://example.com
google_analytics: 'UA-166928354-2' # agorahub-pen0
gh_team: orgs/agorahub/teams/pen
gh_repo: agorahub/pen0

# Build settings
markdown: kramdown
theme: minima
plugins:
  - jekyll-feed

excerpt_separator: <!--more-->
collections_dir: _collections
collections:
  columns:
    output: true
  heros:
    output: true

# Social media
github:   agorahub
reddit: u/agoradao
twitter:  agoradao
telegram: agorahub
#linkedin: linkedin
#facebook: facebook
