title: The Republic of Agora
description: UNITE THE PUBLIC ♢ VOL.14 © MMXXII
baseurl: "/pen0" # the subpath of your site, e.g. /blog
url: "https://agorahub.github.io" # the hostname & protocol, e.g. http://example.com
google_analytics: 'UA-166928354-2' # agorahub-pen0
gh_team: orgs/agorahub/teams/pen
gh_repo: agorahub/pen0

# Build settings
markdown: kramdown
theme: minima
feed:
  posts_limit: 50
  collections:
    heros:
      path: "/heros.xml"
    columns:
      path: "/columns.xml"
    hkers:
      path: "/hkers.xml"
plugins:
  - jekyll-feed
  - octopress-paginate

excerpt_separator: <!--more-->
collections_dir: _collections
collections:
  heros:
    output: true
  columns:
    output: true
  hkers:
    output: true

# Social media
github:   agorahub
reddit: u/agoradao
twitter:  agoradao
telegram: agorahub
#linkedin: linkedin
#facebook: facebook
